version: '2'
networks:
  default:
    name: kafka_default
services:
  app:
    container_name: product-microservice
    build: .
    env_file: .env
    environment:
      - DB=
      - PORT=8003
      - KAFKA_BROKER=broker:29092
    ports:
      - 8003:8003